apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesd12212cd-webserver
  namespace: tesd12212cd
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tesd12212cd-secret
              key: userpassword
        image: gcr.io/pc-api-6479467557629758909-343/tesd12212cd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: tesd12212cd-pvc-sym-m
          mountPath: /var/www/upload/image
      volumes:
      - name: tesd12212cd-pvc-sym-m
        persistentVolumeClaim:
          claimName: tesd12212cd-pvc-sym-uploud
---
apiVersion: v1
kind: Service
metadata:
  name: tesd12212cd-web-service
  namespace: tesd12212cd
  labels:
    run: tesd12212cd-web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
---
apiVersion: v1                  
kind: PersistentVolumeClaim     
metadata:                       
   name: tesd12212cd-pvc-sym-uploud
   namespace: tesd12212cd
spec:                           
   accessModes:                  
   - ReadWriteOnce              
   resources:                   
      requests:                 
         storage: 1Gi   
